/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ccqsohkcdntwuycmlpvu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcXNvaGtjZG50d3V5Y21scHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDE3NTAsImV4cCI6MjA3NzMxNzc1MH0.VAe6ml3kSkQ4Mq5d_2U-0F_yEGXxwmlK-pD23ZNQbcc"